import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Header from "@/components/UI/layout/header";
import {Providers} from "@/providers/provider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Tatarian Kitchen",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <Providers>
            <Header/>
            <main className='flex flex-col items-center justify-start h-[100vh] w-full'>
                {children}
            </main>
            <footer className='flex justify-center items-center h-[80px]'>
                Generated by create next app
            </footer>
        </Providers>
        </body>
        </html>
    );
}
