import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Header from "@/components/UI/layout/header";
import {Providers} from "@/providers/provider";
import {SessionProvider} from "next-auth/react";
import {auth} from "@/auth/auth";
import {AppLoader} from "@/hoc/app-loader";
import Footer from "@/components/UI/layout/footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Tatarian Kitchen",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {

    const session = await auth();
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <Providers>
            <SessionProvider session={session}>
                <AppLoader>
                    <Header/>
                    <main className='flex flex-col items-center justify-start h-[100vh] w-full'>
                        {children}
                    </main>
                    <Footer/>
                </AppLoader>
            </SessionProvider>
        </Providers>
        </body>
        </html>
    );
}
